dist: bionic

language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"

install:
  - pip install -r requirements.txt
  - python setup.py install

addons:
  apt:
    packages:
    - imagemagick
    - gcc-mingw-w64
    - make

script:
  - cd tests/ && make
  - python -m unittest discover . --verbose
  - cd ..  # otherwise deploy stage fails

deploy:
  provider: pypi
  # Enable this to deploy to test server
  server: https://testpypi.python.org/pypi
  user:
    secure: Ql6ihu5MDgWuAvT9NYfriGUYGhHpsqwXfZHWDQT+DfRjOqHo9QT7PnfexeBoe6L6cYUkEnIrnAXKtBXGy6UmyvfrnvBl68877dLVuoC8PfQ4J0ej7TVnCJmT/LwRqFvzZXkeg4CIlJsVJ6pvrPHXQBDPH1rj/rWCucchrofmps8=
  password:
    secure: JOHSaZDPCImV/TlQ7hqKLzEvxY4/gpYGlZlOvxgFEd/k/sGk13sva1MfQkOh7Fgjblhk/CHt59wVKXa0VaylRugFQnXb+NYNrxYON0IRVsKON20XaLXg7qsyKCS4ml+7cd2KvM8a6LVO9078yLWAhTZkZ69nLIRZwFbmL5+mep4=

  on:
    tags: true
    python: '3.8'
  # Skip cleanup because we write version.py as part of the build
  skip_cleanup: true

notifications:
  email: false
